### ISSUE TITLE
On windows, get filepaths with both forward and backwards slashes (causes errors)

### ISSUE THREAD

**Issue by coler-j** [paulocheque/epub-meta#7]
For instance, in the `collector._discover_cover_image()` function I have the following:

base_dir = OEBPS
filepath (for cover) = Images/Art-Canada-Institute_Alex-Colville_img_0.jpg

Then on this line they are joined together:
`content = zf.read(os.path.join(base_dir, filepath))`

Which yields this:
`OEBPS\Images/Art-Canada-Institute_Alex-Colville_img_0.jpg`

Which results in this error:
`KeyError: "There is no item named 'OEBPS\\\\Images/Art-Canada-Institute_Alex-Colville_img_0.jpg' in the archive"`

**Comment by coler-j** [comment]
Ah, I see this is fixed with normpath but not pushed to the pip version.......?

**Comment by paulocheque** [comment]
Published as 0.0.7
